### ISSUE TITLE
What is the meaning of a CoC operating system?

### ISSUE THREAD

**Issue by atennapel** [TimJSwan89/FoxieOS#1]
Can you describe the ideas you had when creating this repo?

**Comment by TimJSwan89** [comment]
From the perspective of cic defined as a PTS, everything undefined by the type system (traditional files, drivers, c blocks) [let's call them llo for lower-level-objects] would be the lambda objects, needing manually proven in their functional inter-relations, while the type structure itself would organize everything and have certain properties by construction. The OS would take advantage of the properties of cic, perhaps having features which automate trying new expressions/code more easily due to the strongly normalizing property as well as being able to reuse 'code' results which has already been evaluated (or 'executed'). Of course, the entire traditional system of runtime vs. compiletime would not exist outside of what I can only describe as a very non-traditional kernel. It would depend on using 256 hashes to uniquely organize cic expressions and persistent stores would be in a database. The OS main functionality, which would be emulated inside the cic as itself essentially just a set of both (1.) a bunch of these expressions and (2.) llo's, would be interfaced with on different iterative levels of abstraction. So, based on "n" levels of type-universe, you would essentially be the compiletime or "developer" compared to n+1 and runtime or "user" compared to n-1.

The concepts of "programming language" "kernel" and "OS" sorta get a bit fudged. The traditional ideas "file" "source code" and "compilation" completely do not exist past the base kernel, which itself would not really be much of an OS. I understand that most of this will not be understood easily at all at this point. Perhaps, with the hashing algorithms included, it is about at the complexity of a cryptocurrency specification. So, I figured a prototype would be best.

Right now, after creating 'Inspiration Basic' in 2014, which is not even available anymore on the App Store as I type this comment, I am working on '(inthpiration),' which is a complex, but yet a relatively much simpler, project. I am hoping it will be a sort of 'stepping stone' toward more possibilities. I couldn't even get the best verifier company in the world to understand these parse tree editing concepts when I worked with them, so I will have to simply work up the 'prototype' ladder, hopefully buying enough passive income to even approach a project like this again.
